services:
    postgres:
                container_name: mic-edu-journal-postgres
                image: postgres:latest
                restart: unless-stopped
                environment:
                    - POSTGRES_USER=mic-edu-journal
                    - POSTGRES_PASSWORD=fd5b47ab8081ef9597d371de
                    - POSTGRES_DB=mic-edu-journal
                ports:
                    - 5432:5432
                volumes:
                    - postgres_data:/var/lib/postgresql/data
    redis:
                container_name: mic-edu-journal-redis
                image: redis:latest
                command: [ "redis-server", "--maxmemory-policy", "noeviction" ]
                restart: unless-stopped
                ports:
                    - 6379:6379
                volumes:
                    - redis_data:/data
    minio:
                container_name: mic-edu-journal-minio
                image: minio/minio:latest
                command: [ "minio", "server", "/data", "--console-address", ":9001" ]
                restart: unless-stopped
                environment:
                    - MINIO_ACCESS_KEY=mic-edu-journal
                    - MINIO_SECRET_KEY=fd5b47ab8081ef9597d371de
                volumes:
                    - minio_data:/data
                healthcheck:
                    test: ["CMD", "mc", "ready", "local"]
                    interval: 5s
                    timeout: 5s
                    retries: 5
volumes:
    postgres_data:
    redis_data:
    minio_data:
    
networks:
    default: {}